name 'sandy-base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sandy-base'
long_description 'Installs/Configures sandy-base'
version '0.1.0'

depends 'chef-client'
depends 'resolver', '~> 1.3.0'
depends 'selinux', '~> 0.9.0'
depends 'chef-sugar', '~> 3.1.0'
depends 'gina-users'
depends 'ntp', '~> 1.8.0'
depends 'omnibus_updater', '~> 1.0.0'
depends 'iptables-ng'
depends 'openssh'
depends 'ssh_known_hosts'
depends 'users'
